"use strict";
let myString = "1";
let myNumber = 1;
let myBoolean = true;
myString = 1;
myNumber = "1";
myBoolean = "false";
let myNull = null;
let myUndefined = undefined;
myNull = 1;
myUndefined = 1;
