'use strict';
const singleQuotes = 'I am singles';
const doubleQuotes = "I'm doubles";
const backticks = `I'am backticks`;
const helloWorld = 'Hello, World!';
const firstName = 'pepita';
const lastName = 'pérez';
const womanName = 'pepita';
const manName = 'pepito';
const hellos = 'Hello ladies, Hello gentlemen, Hello World!';
const strObj = new String('Hello, Object!');
const helloSpaces = '   Hello!   ';

// console.log(singleQuotes);
// console.log(doubleQuotes);
// console.log(backticks);

//console.log(helloWorld);
//console.log(helloWorld.length);
//console.log(helloWorld[0]);
//console.log(helloWorld[12]);

//console.log(helloWorld.at(0));
//console.log(helloWorld.at(-1));
//console.log(helloWorld.charAt(0));
//console.log(helloWorld.charAt(12));
//console.log(helloWorld.charCodeAt(0));
//console.log(firstName.concat(' ', lastName, ' ', helloWorld));
//console.log(helloWorld.endsWith('!'));
//console.log(String.fromCharCode(72));
//console.log(helloWorld.includes('!'));
//console.log(helloWorld.indexOf('l'));
//console.log(helloWorld.lastIndexOf('l'));
//console.log(womanName.localeCompare(firstName));
//console.log(womanName.localeCompare(manName));
//console.log(manName.localeCompare(womanName));
//console.log(hellos.match('xxx'));
//console.log(hellos.match('ladies'));
//console.log(hellos.match('ello'));
//console.log(helloWorld.repeat(3));
//console.log(helloWorld.replace(', ', '-'));
//console.log(helloWorld.search('l'));
//console.log(helloWorld.slice(7));
//console.log(helloWorld.split(''));
//console.log(helloWorld.split(', '));
//console.log(helloWorld.startsWith('h'));
//console.log(helloWorld.startsWith('H'));
//console.log(helloWorld.substr(6));
//console.log(helloWorld.substring(6, 12));
//console.log(helloWorld.toLocaleLowerCase());
//console.log(helloWorld.toLocaleUpperCase());
//console.log(helloWorld.toLowerCase());
//console.log(strObj);
//console.log(strObj.toString());
//console.log(helloWorld.toUpperCase());
//console.log(helloSpaces);
//console.log(helloSpaces.trim());
//console.log(helloSpaces.trimEnd());
//console.log(helloSpaces.trimStart());
//console.log(helloWorld.valueOf());
//console.log(strObj.valueOf());
