'use strict';
const helloWorld = 'Hello, World!';
const firstName = 'pepita';
const lastName = 'pérez';
const womanName = 'pepita';
const manName = 'pepito';
const hellos = 'Hello ladies, Hello gentlemen, Hello World!';
// console.log(helloWorld);
// console.log(helloWorld.length);
// console.log(helloWorld[0]);
// console.log(helloWorld[12]);
// console.log(helloWorld.charAt(0));
// console.log(helloWorld.charAt(12));
// console.log(helloWorld.charCodeAt(0));
// console.log(firstName.concat(' ', lastName, ' ', helloWorld));
// console.log(helloWorld.constructor);
// console.log(helloWorld.endsWith('!'));
// console.log(String.fromCharCode(72));
// console.log(helloWorld.includes('!'));
// console.log(helloWorld.indexOf('l'));
// console.log(helloWorld.lastIndexOf('l'));
// console.log(womanName.localeCompare(firstName));
// console.log(womanName.localeCompare(manName));
// console.log(manName.localeCompare(womanName));
// console.log(hellos.match('xxx'));
// console.log(hellos.match('ladies'));
// console.log(hellos.match('ello'));
