# Data types
print(type("c"))
print(type("word"))
print(type("n words"))
print(type(0))
print(type(0.1))
print(type(1 + 1j))
print(type(["a", "b", "c"]))
print(type([1, 2, 3]))
print(type({"one": 1}))
print(type({"one", 1}))
print(type(("one", 1)))
print(type(True))
print(type(False))
print(type(print("")))
