# Operators
print(6 + 2)
print("Hello" + " " + "World!")
print(6 - 2)
print(6 * 2)
print("Hello" * 2)
print(6**2)
print(6 / 2)
print(6 // 2)
print(6 % 2)
print(6 > 2)
print(6 >= 2)
print(6 < 2)
print(6 <= 2)
print(6 == 2)
print(6 != 2)
print("Hello" > "Halo")
print("Hello" >= "Halo")
print("Hello" < "Halo")
print("Hello" <= "Halo")
print("Hello" == "Halo")
print("Hello" != "Halo")
print(0 == 0 and 1 == 1)
print(0 < 1 and 1 > 0)
print(0 == 0 or 1 < 0)
print(0 > 1 or 0 < 1)
print(not (0 == 0 and 1 == 1))
