# Strings
word = "Hi"
print(word)
a, b = word
print(a)
print(b)
print("works")
print("works"[::-1])
print("works"[:1])
print("works"[1:])
print("works"[-1])
print("works"[1:4])
print("works".capitalize())
print("works".upper())
print("works".lower())
print("works".count("r"))
print("works".isnumeric())
print("works".islower())
print("works".isupper())
print("works".startswith("w"))
