# tuples
my_tuple = tuple()
print(type(my_tuple))
my_other_tuple = ()
print(type(my_other_tuple))
my_tuple = ("one", "two", "three", "four", "five")
print(my_tuple)
my_other_tuple = ("monday", "tuesday", " wednesday", "thursday", "friday")
print(my_other_tuple)
my_tuple = ("one", "two", "three", "four", "five", "one")
print(my_tuple)
print(my_tuple.index("three"))
print(my_tuple.index("one"))
